"""initial tables

Revision ID: 9ef13ee0fd51
Revises: 4dadfc879016
Create Date: 2025-12-16 19:57:29.656645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ef13ee0fd51'
down_revision: Union[str, Sequence[str], None] = '4dadfc879016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ledger', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               schema='accounting')
    op.alter_column('company', 'default_bank_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True,
               schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'default_bank_details',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='identity')
    op.alter_column('ledger', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='accounting')
    # ### end Alembic commands ###
